### PR TITLE
Linter setup for Project

### PR DESCRIPTION
**Pull request by t-bello7**
- add eslint, hint and stylint configurations to the project
- add HTML and style

### CODE REVIEW

**Review by JuliCarracedo — CHANGES_REQUESTED** [review]
Hi @t-bello7 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

[✔️](https://emojipedia.org/check-mark/) Professional README
[✔️](https://emojipedia.org/check-mark/) Descriptive PR and commits
[✔️](https://emojipedia.org/check-mark/) Great first project!

## Required Changes ♻️
_Check the comments under the review._

- [ ] Both stylelint and eslint are failing on GitHub Actions. It is a requirement to have them passing on your PR. you can check the [linters documentation](https://github.com/microverseinc/linters-config/tree/master/html-css) to understand how to check your code for errors and how to fix them locally. Keep in mind that this is now just a required change, but further in the program, failing linters are a reason for invalidating a project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by t-bello7** [comment]
@JuliCarracedo  Thank you for reviewing. I have made the changes to the project as required.

**Review by topeogunleye — APPROVED** [review]
### Hi @t-bello7, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
congratulations
> 
> ## [Optional] suggestions:
> * [ ]  Please check my inline comments.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by t-bello7** [comment]
@topeogunleye Thank you for your review. You gave me an optional suggesstion to check my in line comments. I have absolutely no idea how to do that.

**Comment by topeogunleye** [comment]
> @topeogunleye Thank you for your review. You gave me an optional suggesstion to check my in line comments. I have absolutely no idea how to do that.

Don't worry about that because I didn't make any inline comments

**Pull request merged**
